CREATE TABLE FOERSTESIDE
(
    foersteside_id NUMBER(19, 0) PRIMARY KEY,
    loepenummer    VARCHAR2(24) UNIQUE,
    dato_opprettet TIMESTAMP NOT NULL,
    uthentet       NUMBER(1, 0) DEFAULT 0,
    dato_uthentet  TIMESTAMP
);

CREATE TABLE FOERSTESIDE_METADATA
(
    foersteside_metadata_id NUMBER(19, 0) PRIMARY KEY,
    foersteside_id          NUMBER(19, 0) NOT NULL,
    key                     VARCHAR2(50)  NOT NULL,
    value                   VARCHAR2(2000)
);

ALTER TABLE FOERSTESIDE_METADATA
    ADD CONSTRAINT FK_FOERSTESIDE
        FOREIGN KEY (foersteside_id)
            REFERENCES FOERSTESIDE;

CREATE SEQUENCE FOERSTESIDE_SEQ START WITH 1000 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE;
CREATE SEQUENCE FOERSTESIDE_METADATA_SEQ START WITH 50000 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE;