kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: {{ APPNAVN }}
  namespace: teamdokumenthandtering
  labels:
    team: teamdokumenthandtering
spec:
  env:
    - name: AZURE_APP_TOKEN_URL
      value: {{AZURE_APP_TOKEN_URL}}
    - name: SPRING_DATASOURCE_URL
      value: {{ SPRING_DATASOURCE_URL }}
    - name: DOKUMENTTYPEINFO_URL
      value: {{ DOKUMENTTYPEINFO_URL }}
    - name: METAFORCEENDPOINT_URL
      value: {{ METAFORCEENDPOINT_URL }}
    - name: DOKMET_SCOPE
      value: {{ DOKMET_SCOPE }}
    - name: NO_NAV_SECURITY_JWT_ISSUER_RESTSTS_DISCOVERYURL
      value: {{ NO_NAV_SECURITY_JWT_ISSUER_RESTSTS_DISCOVERYURL }}
    - name: NO_NAV_SECURITY_JWT_ISSUER_RESTSTS_ACCEPTED_AUDIENCE
      value: {{ NO_NAV_SECURITY_JWT_ISSUER_RESTSTS_ACCEPTED_AUDIENCE }}
  image: {{ image }}
  ingresses:
        {{#each INGRESSES}}
          - {{this }}
        {{/each}}
  liveness:
    path: /actuator/health/liveness
    port: 8080
    initialDelay: 30
    failureThreshold: 10
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /actuator/health/readiness
    port: 8080
    initialDelay: 30
    timeout: 3
  replicas:
    min: {{ MIN_REPLICAS }}
    max: {{ MAX_REPLICAS }}
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      memory: 256Mi
  vault:
    enabled: true
    paths:
      - kvPath: {{ SRVFOERSTESIDEGENERATOR }}
        mountPath: /var/run/secrets/nais.io/srvfoerstesidegenerator
      - kvPath: {{ FOERSTESIDEGENERATORDB }}
        mountPath: /var/run/secrets/nais.io/foerstesidegeneratorDB
  azure:
    application:
      enabled: true
      claims:
        extra:
          - "NAVident"
          - "azp_name"
  accessPolicy:
    inbound:
      rules:
      {{#each AZURE_IAC_RULES}}
        - application: {{app}}
          namespace: {{namespace}}
          cluster: {{cluster}}
      {{/each}}
  webproxy: true
